---
- name: Install telescope.nvim plugin
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.config/nvim/lua/plugins.lua
    line: "use {'nvim-telescope/telescope.nvim', requires = {{'nvim-lua/plenary.nvim'}}}"
